### ISSUE TITLE
Connection closed error 

### ISSUE THREAD

**Issue by groovybayo** [oliverlloyd/jmeter-ec2#10]
Hi Oliver – Nice work on the script. I am experiencing the same issues with lost connection when copying over the install.sh.

```
copying install.sh to 1 server(s)…lost connection
.grep: /Users/workspace/testing-ws/jmeter-ec2/sample-project/1364519238*scpinstall.out: No such file or directory
```

I have verified my security group is configured correctly and can ssh into the box by doing a telnet ping on 22

```
telnet ec2-23-23-69-1.compute-1.amazonaws.com 22 ⏎
Trying 23.23.69.1…
 Connected to ec2-23-23-69-1.compute-1.amazonaws.com.
 Escape character is ‘^]’.
 SSH-2.0-OpenSSH_5.9p1 Debian-5ubuntu1
  ^C
```

However, the scp of install.sh fails and I can’t get past that point. I have even put a sleep 60s as suggested by Zack on (http://www.http503.com/2012/run-jmeter-on-amazon-ec2-cloud/), to no avail.

Any ideas why this might be happening? Is there a work around?

Thanks in advance.

**Comment by DmitriyMazur** [comment]
>I fight with the same issue. Solution in my case was to change security group rules. I edit service parameters in inbound rules section. Added myIP (or customIP or anywhere) to include my public IP address.

**Comment by tegryan** [comment]
For anyone having troubles with the infamous  "copying install.sh to 1 server(s)…lost connection" issue and are using EC2 try changing your security group to be any IP on port 22, not just the host you are trying to access from.

I can't explain it, but from one EC2 host to the Jmeter host I could SSH, but not SCP.  I tried all suggestions in thread and others and nothing worked until I did that.  I suspect you couldn't reproduce it Oliver because you were not going from EC2 host to EC2 host (just a guess).

I also tried disabling MOTD, changing to the ec2-user (I need to use ubuntu), creating a .hushlogin file and so on.  If you recreate the SCP command, add -vvv and get rid of -q while the jmeter node is up you might get some additional info.  Certainly if the permissions on the .pem file are wrong that will at least tell you.

**Comment by manusovich** [comment]
I also meet this issue and my fault was because i changed default user to ec2-user (instead of ubuntu) in properties and forgot to change AMI_ID. So, my instances didn't have such user (ec2-user). My bad. As soon as i change user back to ubuntu, everything starts working well.
