### ISSUE TITLE
Test don't start with default amazon Ubuntu instance

### ISSUE THREAD

**Issue by Firfi** [oliverlloyd/jmeter-ec2#37]
I use Ubuntu Server 14.04 LTS (HVM), SSD Volume Type - ami-5189a661 . 

It starting correctly and being active during test, but all the time I see only 

`waiting for the test to start...to stop the test while it is running, press CTRL-C`. This message doesn't disappear, and it can hang there one hour.

If I do ctrl+c, script exiting successfully, destroying temporary instance, and returns empty report.

Any suggestions what can cause this problem?

**Comment by oliverlloyd** [comment]
If I had to have a guess I'd say jmeter is failing to start. Have a look to see if there are any *.out files in the directory where you are running the script. The `[blah]jmeter.out` file(s) should contain the stdout from the command to execute jmeter, if there were any errors with this they will be here. Maybe this instance is missing a pre-requisit like java. Does it work if you use a different ami such as `ami-e1e8d395`?

It's also possible that the command to execute jmeter failed before the jmeter process was started. The best way to test this is to spin up an instance, jump onto it, and try to run jmeter directly on the instance.

Another possibility is connectivity issues but this is less likely because you've got passed the install stages which means the script was able to talk to the instance that was spun up - it's just not hearing back from jmeter.

You can also try running the script in debug mode by passing `-x` when running it or editing jmeter-ec2.sh to have `set -x` at the top. This will print the commands being run and, if you don't terminate the instances by passing `terminate=FALSE` as an option then you can use this log to try rerunning these commands manually.

If you still have no luck print a copy of your output here with the -x debug option set.

**Comment by supakitk** [comment]
@oliverlloyd  Thanks for the great script!

I have a few suggested changes to the documentation. 

1. Amazon has deprecated EC2_PRIVATE_KEY and EC2_CERT in a favor of AWS_ACCESS_KEY and AWS_SECRET_KEY for API Tool Restful call.

2. ami-e1e8d395 no longer available to use. End up have to use ami-5189a661 (Ubuntu Server 14.04 LTS) and also t1.micro is not supported by the new AMI have to change it to t2.micro

**Comment by oliverlloyd** [comment]
@supakitk These sound like good ideas. I'm not actively working on this script at the moment so would you be willing to make the changes and send through a pull request?

**Comment by oliverlloyd** [comment]
Merged, thanks
