### ISSUE TITLE
Data File location

### ISSUE THREAD

**Issue by gauravpatel2016** [oliverlloyd/jmeter-ec2#72]
Hi,

I have CSV data set config in my jmeter script which points to CSV. I got 
The path ${__P(DataFilePath)}/${__P(CSVFile)} contains a $ char, this currently fails the awk sub command. You'll have to remove these from all filepaths. Sorry.

Is there a way I can pass parameter in CSV data set config. I have everything driven by properties file in Jmeter.

Thanks in advance

**Comment by oliverlloyd** [comment]
The reason this isn't possible is because you need the jmeter engine to parse whatever reference or variable you pass in - and this is not available when I am reading the xml, I'm just using bash.

Note. I need an explicit reference to the csv because I read it into memory and then divide the contents of the file between each slave. One option would be to offer the ability to turn this feature off - I'll look at that. But for now it is explicitly not allowed to do what you're doing.
